### ISSUE TITLE
two python3 incompatibilities and a suggestion

### ISSUE THREAD

**Issue by bcrowell** [olemb/readlisp#1]
Thanks for writing this and making it open source -- very helpful!

Lines 156, 168, 170, and 172 have a tab used as a substitute for 8 spaces (2 levels of indentation), which causes an error in python3:

$ python3 readlisp.py 
  File "readlisp.py", line 156
    return '(%s)' % ' '.join(map(writelisp, obj))
                                                ^
TabError: inconsistent use of tabs and spaces in indentation

By default when the program is run as a standalone program, it reads input from test.lisp. IMO a better default for standard use would be to read from stdin.

StringIO is used in one place, and StringIO is not present in python3. There is some material here on how to modify code using StringIO so that it is compatible with both python2 and python3: https://stackoverflow.com/questions/11914472/stringio-in-python3 . I think the try-catch method shown in nobar's answer is probably a good one.

**Comment by olemb** [comment]
Thanks for your suggestions! I have pushed a new version with all of your changes.

The mixed tabs and spaces is something that emacs did back in the day. I came across this when I updated another project today (minesweeper).

I wrote readlisp back in 2006 and haven't used or updated it since but I decided to put it up here on GitHub. I'm glad you find it useful!
